name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/qtqgyt/TheLinuxFiles/main/.data/hpatchz
          chmod +x hpatchz
          wget -O - https://api.github.com/repos/qtqgyt/TheLinuxFiles/contents/Ubuntu | jq -c '.[] | {download_url: .download_url, path: .path}' | while IFS= read -r entry; do
            url=$(echo "$entry" | jq -r '.download_url')
            path=$(echo "$entry" | jq -r '.path')
            mkdir -p "$(dirname "$path")"
            echo "Downloading $download_url to $path"
            wget -O "$path" "$download_url"
          done
          find "Ubuntu/" -maxdepth 1 -mindepth 1 -type f -name "*.*" | while IFS= read -r i; do
            ./hpatchz "Ubuntu/base" "$i.patch" "$i.iso"
          done

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
