name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/qtqgyt/TheLinuxFiles/main/.data/hpatchz
          wget -O - https://api.github.com/repos/qtqgyt/TheLinuxFiles/contents/Ubuntu | jq -r '.[].download_url'
          find "Ubuntu/" -maxdepth 1 -mindepth 1 | while IFS= read -r i; do
            echo $i
            ./hpatchz "Ubuntu/base" "$i.patch" "$i.iso"
          done

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
